#!/usr/bin/env python3
"""Generate/check docs/kb/INDEX.md from every docs/kb/*.md entry's
frontmatter — the single source of truth for both `make kb-index` (write)
and `scripts/run_regress.py`'s staleness check (read-only compare), so the
two can never drift apart by each re-implementing the generation logic.

Usage:
    kb_index.py --write   # regenerate docs/kb/INDEX.md (make kb-index)
    kb_index.py --check   # exit 1 + print diff if INDEX.md is stale
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
KB_DIR = ROOT / "docs" / "kb"
INDEX_PATH = KB_DIR / "INDEX.md"
_SKIP = {"README.md", "INDEX.md"}


def _parse_frontmatter(path: Path) -> dict:
    text = path.read_text()
    if not text.startswith("---\n"):
        raise ValueError(f"{path}: missing frontmatter (must start with '---')")
    end = text.index("\n---\n", 4)
    raw = text[4:end]
    fields: dict[str, str] = {}
    for line in raw.splitlines():
        if not line.strip() or ":" not in line:
            continue
        key, _, value = line.partition(":")
        fields[key.strip()] = value.strip()
    for required in ("title", "tags", "confidence"):
        if required not in fields:
            raise ValueError(f"{path}: frontmatter missing required field '{required}'")
    return fields


def _entries() -> list[tuple[str, dict]]:
    out = []
    for path in sorted(KB_DIR.glob("*.md")):
        if path.name in _SKIP:
            continue
        out.append((path.name, _parse_frontmatter(path)))
    return out


def render_index() -> str:
    entries = _entries()
    lines = [
        "# Knowledge Base Index",
        "",
        "Generated by `make kb-index` from every docs/kb/*.md entry's "
        "frontmatter — do not hand-edit, it will be overwritten.",
        "",
        f"{len(entries)} entries.",
        "",
        "| File | Title | Tags | Confidence |",
        "|---|---|---|---|",
    ]
    for filename, fm in entries:
        tags = fm["tags"].strip("[]")
        lines.append(f"| [{filename}]({filename}) | {fm['title']} | {tags} | {fm['confidence']} |")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    mode = sys.argv[1] if len(sys.argv) > 1 else "--write"
    rendered = render_index()

    if mode == "--write":
        INDEX_PATH.write_text(rendered)
        print(f"wrote {INDEX_PATH} ({len(_entries())} entries)")
        return 0

    if mode == "--check":
        if not INDEX_PATH.exists():
            print(f"FATAL: {INDEX_PATH} does not exist — run 'make kb-index'")
            return 1
        current = INDEX_PATH.read_text()
        if current != rendered:
            print(
                f"FATAL: {INDEX_PATH} is stale (doesn't match docs/kb/*.md "
                f"frontmatter) — run 'make kb-index' and commit the result."
            )
            return 1
        print(f"{INDEX_PATH} is up to date ({len(_entries())} entries)")
        return 0

    print(f"usage: {sys.argv[0]} [--write|--check]")
    return 2


if __name__ == "__main__":
    sys.exit(main())
